### ISSUE TITLE
Backtracking doesn't find last event when no progress

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#109]
https://github.com/akka/akka-persistence-r2dbc/runs/4079463405?check_suite_focus=true#step:7:2415

```
[2021-11-02 11:49:02,221] [INFO] [akka.actor.testkit.typed.scaladsl.LogCapturing] [] [] [pool-1-thread-1-ScalaTest-running-EndToEndSpec] - Logging finished for test [akka.projection.r2dbc.EndToEndSpec: A R2DBC projection with eventsBySlices source must handle all events exactlyOnce] that [Failed(java.lang.AssertionError: timeout (20 seconds) while expecting 200 messages (got 194))]
2414
<-- [akka.projection.r2dbc.EndToEndSpec: A R2DBC projection with eventsBySlices source must handle all events exactlyOnce] End of log messages of test that [Failed(java.lang.AssertionError: timeout (20 seconds) while expecting 200 messages (got 194))]
2415
[info] - must handle all events exactlyOnce *** FAILED *** (26 seconds, 502 milliseconds)
2416
[info]   java.lang.AssertionError: timeout (20 seconds) while expecting 200 messages (got 194)
2417
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
2418
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1(TestProbeImpl.scala:262)
2419
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1$adapted(TestProbeImpl.scala:257)
2420
[info]   at scala.collection.immutable.Range.map(Range.scala:59)
2421
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages_internal(TestProbeImpl.scala:257)
2422
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages(TestProbeImpl.scala:247)
2423
[info]   at akka.projection.r2dbc.EndToEndSpec.$anonfun$new$2(EndToEndSpec.scala:217)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4093435167?check_suite_focus=true#step:7:2536

**Comment by johanandren** [comment]
[logs_233.zip](https://github.com/akka/akka-persistence-r2dbc/files/7482050/logs_233.zip)

**Comment by patriknw** [comment]
here is another (with the new logging) https://github.com/akka/akka-persistence-r2dbc/runs/4115863924?check_suite_focus=true#step:7:3981

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4118242734?check_suite_focus=true#step:7:2505

**Comment by patriknw** [comment]
ok, in the [latest logs](https://github.com/akka/akka-persistence-r2dbc/runs/4118242734?check_suite_focus=true#step:7:2505) I see what happened here. It's missing the very last event. First it missed seqNr 2 for p0 and therefore rejected 3..10. Then backtracking finds seqNr 2..9 as expected.

The the normal query is repeatadly querying at the offset of the one with seqNr 10, but that is filtered as expected because the normal query has already emitted it:
```
2021-11-05T14:46:15.2697494Z [2021-11-05 14:45:55,779] [DEBUG] [akka.persistence.r2dbc.query.scaladsl.R2dbcReadJournal] [] [] [EventSourcedEndToEndSpec-akka.actor.default-dispatcher-6] - filtering [TestEntity-1|p0] [10] as db timestamp is the same as last offset and is in seen [Map(TestEntity-1|p0 -> 10)]
```

Additional backtracking attempts will not find it because it will not overtake the offset of the normal query. It is stuck here until there would any other event that moves the offset of the normal query forward so that the backtracking can find it.

I'll have to think some about what the solution would be, but maybe it would be ok to let backtracking offset be `<=` the normal offset instead of `<`.
