### ISSUE TITLE
Store only one snapshot?

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#113]
Why do we store snapshots as append only and keep old snapshots?

I don't see a compelling reason for that and suggest that we use upsert to replace the snapshot for a persistenceId.

I would guess the reason is from the Cassandra plugin where snapshots can be stored with a lower consistency level or that append only is much more preferred for Cassandra.

The reason could also be the early ideas of replaying to a certain point in time (not always latest). The different parameters in the SnapshotCriteria. We don't need to support that for snapshots in my opinion.

**Comment by johanandren** [comment]
We have this whole API and internal machinery both for snapshot retention and recovery in `EventSourcedBehavior` so I was wrong that it is only for classic persistence, but I think it should be fine to not support all that in this plugin anyway.
