### ISSUE TITLE
Utility to replace numbered sql parameters

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#135]
To improve the code readability we can implement a small string search and replace utility that replaces `$` with numbered `$1`, `$2`, `$3`.

**Comment by johanandren** [comment]
Is it up to the r2dbc plugin to support named parameter to start with and the postgres one doesn't (if so, could we contribute that perhaps)?

**Comment by patriknw** [comment]
In the end I want to bind with index because that is less lookups when binding parameters. Probably a very minor performance difference, but anyway.
