### ISSUE TITLE
Add R2DBC support (IBM DB2/UDB)

### ISSUE THREAD

**Issue by JustinPihony** [akka/akka-persistence-r2dbc#222]
### Short description

Add the ability to store the offset in DB2 (akin to https://doc.akka.io/docs/akka-projection/current/cassandra.html and others)

### Details

Possibly utilize https://github.com/usaa/reactive-db-bridge?

**Comment by JustinPihony** [comment]
> @JustinPihony, the R2DBC plugin is hosting the projection support (for now) https://github.com/akka/akka-persistence-r2dbc
> 
> So I guess we will need to add support for DB2 there instead.
> 
> We can eventually move the projection part here, but that's not yet planned or decided.

Migrated :)

**Comment by patriknw** [comment]
We'll track this elsewhere.
