### ISSUE TITLE
Projection timestamp offset store does not have projection_key in its primary key

### ISSUE THREAD

**Issue by odd** [akka/akka-persistence-r2dbc#242]
The `akka_projection_timestamp_offset_store` table has a primary key which does not contain the `projection_key` column.

Current table definition for Postgres:
```
CREATE TABLE IF NOT EXISTS akka_projection_timestamp_offset_store (
  projection_name VARCHAR(255) NOT NULL,
  projection_key VARCHAR(255) NOT NULL,
  slice INT NOT NULL,
  persistence_id VARCHAR(255) NOT NULL,
  seq_nr BIGINT NOT NULL,
  -- timestamp_offset is the db_timestamp of the original event
  timestamp_offset timestamp with time zone NOT NULL,
  -- timestamp_consumed is when the offset was stored
  -- the consumer lag is timestamp_consumed - timestamp_offset
  timestamp_consumed timestamp with time zone NOT NULL,
  PRIMARY KEY(slice, projection_name, timestamp_offset, persistence_id, seq_nr)
);
```
Proposed table definition for Postgres:
```
CREATE TABLE IF NOT EXISTS akka_projection_timestamp_offset_store (
  projection_name VARCHAR(255) NOT NULL,
  projection_key VARCHAR(255) NOT NULL,
  slice INT NOT NULL,
  persistence_id VARCHAR(255) NOT NULL,
  seq_nr BIGINT NOT NULL,
  -- timestamp_offset is the db_timestamp of the original event
  timestamp_offset timestamp with time zone NOT NULL,
  -- timestamp_consumed is when the offset was stored
  -- the consumer lag is timestamp_consumed - timestamp_offset
  timestamp_consumed timestamp with time zone NOT NULL,
  PRIMARY KEY(slice, projection_name, projection_key, timestamp_offset, persistence_id, seq_nr)
);
```

I imagine the same change should be done to the Yugabyte as well.

**Comment by patriknw** [comment]
When/why is that needed?
`projection_name`, `persistence_id`, `seq_nr` should make it unique.

slice is just derived from persistence_id

There shouldn't be two different projection instances with same projection_name that are consuming the same slice.

That said, I have seen unique constraint violations that I don't really understand yet.

```
io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23505] duplicate key value violates unique constraint "akka_projection_timestamp_offset_store_pkey"
io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23505] duplicate key value violates unique constraint "akka_projection_timestamp_offset_store_pkey"
```

**Comment by odd** [comment]
We have several projections using the same `projection_name` (they all consume the same underlying entity so the name is something like `'shopping-cart-view'`) but use different `projection_key`s since they all need to consume the full set of events from the entity (so the `projection_key` is use-case specific like `'email-sender'` or `'analyzer'`). Perhaps this is bad style and we should instead put the use-case specific part into the `projection_name` as well (i.e. `'shopping-cart-email-sender'` and `'shopping-cart-analyzer '`). If so this issue might be moot (unless there are other valid reasons that the `projection_key` might differ even though the `projection_name`, `persistence_id` and `seq_nr` are the same as the unique constraint violations suggests).

**Comment by patriknw** [comment]
Ok, then it is a misunderstanding of how `projection_name` should be used. In your case you should have a unique `projection_name` for each, like 'shopping-cart-email-sender' and 'shopping-cart-analyzer '.

In the other offset store implmentations, such as -jdbc and -cassandra, the `projection_key` is used to make the `projection_name` + `projection_key` unique. They store only one row for the latest offset for each projection instance.

The implementation here is quite different for timestamp offsets so the `projection_key` isn't really used, aside from useful debugging information.

In this way it will also be easier to change the number of projection instances (slice distribution), but still keep the same stored offset rows.

**Comment by odd** [comment]
Ok, I'll fix our usage according to your recommendation. Whether the `projection_key` should be part of the primary key or not, I don't have any opinion on anymore so please close this issue (and the related PRs) if you feel the current primary key definition is the right one.
Thanks for the quick feedback!
