### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [akka/akka-persistence-r2dbc#254]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by patriknw** [comment]
We want something low level where we have full control of the SQL. Using an OR-mapper with a higher level of abstraction might be more convenient for an application but not for this library.
