### ISSUE TITLE
Monitor consumer lag

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#30]
* timestamp_offset is the db_timestamp of the original event
* last_updated is when the offset was stored
* the consumer lag is last_updated - timestamp_offset

It would be nice to periodically query and log consumer lag (can be done before delete).

**Comment by octonato** [comment]
And if, in addition to logging, we keep this info in memory and queryable?

**Comment by patriknw** [comment]
It's also part of the `TimestampOffset`. Diff between `readTimestamp` and `timestamp`. We should already have access to this via the Akka Projections `Telemetry` SPI.

**Comment by patriknw** [comment]
I don't think we need anything more here.
