### ISSUE TITLE
Failed: Scala 3 nightly builds

### ISSUE THREAD

**Issue by pvlugter** [akka/akka-persistence-r2dbc#360]
Nightly build for Scala 3, introduced in #359, is failing to build. Last example:

https://github.com/akka/akka-persistence-r2dbc/actions/runs/4272941578/jobs/7438501363

**Comment by johanandren** [comment]
When I was looking in to Scala 3 for r2dbc the Scala Long vs Java Long was one of the things I struggled with and never really figured out how to work around @sebastian-alfers

**Comment by sebastian-alfers** [comment]
So, I think this is because we run tests for `migrationTests` with scala3, which is not supported currently. I think that should be fixed, before we look into other problems, e.g. with Scala Long vs Java Long.

**Comment by sebastian-alfers** [comment]
Also, nightlies are working again: https://github.com/akka/akka-persistence-r2dbc/actions/runs/4299431447
