### ISSUE TITLE
failed: EventsBySliceStartingFromSnapshotSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#417]
With Yugabyte

https://github.com/akka/akka-persistence-r2dbc/actions/runs/5446181384/jobs/9906686525?pr=416#step:7:1759

```
[info] - should retrieve from several slices *** FAILED *** (12 seconds, 51 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds. (EventsBySliceStartingFromSnapshotSpec.scala:376)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.persistence.r2dbc.query.EventsBySliceStartingFromSnapshotSpec$$anon$7.<init>(EventsBySliceStartingFromSnapshotSpec.scala:376)
[info]   at akka.persistence.r2dbc.query.EventsBySliceStartingFromSnapshotSpec.$anonfun$new$22(EventsBySliceStartingFromSnapshotSpec.scala:313)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/5484144728/jobs/9991310307#step:7:1771

**Comment by johanandren** [comment]
Yuga https://github.com/akka/akka-persistence-r2dbc/actions/runs/5475875725/jobs/9972593454?pr=423#step:7:1764

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/5485588403/jobs/9994578790#step:7:1781

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/5494438452/jobs/10013231547?pr=423#step:7:1978

**Comment by pvlugter** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/5581843043/jobs/10200433779?pr=429#step:7:296

**Comment by pvlugter** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/5791058537/job/15695216672#step:7:1771

**Comment by patriknw** [comment]
Might be same as in https://github.com/akka/akka-persistence-r2dbc/issues/234
